// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TeaManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128045735_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeaManagement.Entities.AccountingTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reversed");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int?>("ReversedId")
                        .HasColumnType("integer")
                        .HasColumnName("reversed_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voucher_no");

                    b.Property<int>("VoucherTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("voucher_type_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.ToTable("transactions", "accounting");
                });

            modelBuilder.Entity("TeaManagement.Entities.AddBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BonusPerKg")
                        .HasColumnType("numeric")
                        .HasColumnName("bonus_per_kg");

                    b.Property<int>("FactoryId")
                        .HasColumnType("integer")
                        .HasColumnName("factory_id");

                    b.Property<int?>("LedgerId")
                        .HasColumnType("integer")
                        .HasColumnName("ledger_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bonus");

                    b.HasIndex("FactoryId")
                        .HasDatabaseName("ix_bonus_factory_id");

                    b.ToTable("bonus", "general_setup");
                });

            modelBuilder.Entity("TeaManagement.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_category_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_product_category");

                    b.ToTable("product_category", "inventory");
                });

            modelBuilder.Entity("TeaManagement.Entities.CoaLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_coa");

                    b.ToTable("coa", "accounting");
                });

            modelBuilder.Entity("TeaManagement.Entities.Ledger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SubParentId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_parent_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger");

                    b.ToTable("ledger", "accounting");
                });

            modelBuilder.Entity("TeaManagement.Entities.NewFactory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text")
                        .HasColumnName("contact_number");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<int>("LedgerId")
                        .HasColumnType("integer")
                        .HasColumnName("ledger_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_factory");

                    b.HasIndex("LedgerId")
                        .HasDatabaseName("ix_factory_ledger_id");

                    b.ToTable("factory", "general_setup");
                });

            modelBuilder.Entity("TeaManagement.Entities.Payable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("StakeholderId")
                        .HasColumnType("integer")
                        .HasColumnName("stakeholder_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payable");

                    b.ToTable("payable", "accounting");
                });

            modelBuilder.Entity("TeaManagement.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_category_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_product_unit_id");

                    b.ToTable("product", "inventory");
                });

            modelBuilder.Entity("TeaManagement.Entities.ProductUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UnitDescription")
                        .HasColumnType("text")
                        .HasColumnName("unit_description");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_name");

                    b.HasKey("Id")
                        .HasName("pk_unit");

                    b.ToTable("unit", "inventory");
                });

            modelBuilder.Entity("TeaManagement.Entities.Receivable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("StakeholderId")
                        .HasColumnType("integer")
                        .HasColumnName("stakeholder_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime>("TxnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("txn_date");

                    b.HasKey("Id")
                        .HasName("pk_receivable");

                    b.HasIndex("StakeholderId")
                        .HasDatabaseName("ix_receivable_stakeholder_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_receivable_transaction_id");

                    b.ToTable("receivable", "accounting");
                });

            modelBuilder.Entity("TeaManagement.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FactoryId")
                        .HasColumnType("integer")
                        .HasColumnName("factory_id");

                    b.Property<decimal>("NetQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("net_quantity");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("WaterQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("water_quantity");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("FactoryId")
                        .HasDatabaseName("ix_sales_factory_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sales_product_id");

                    b.ToTable("sales", "inventory");
                });

            modelBuilder.Entity("TeaManagement.Entities.Stakeholder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("LedgerId")
                        .HasColumnType("integer")
                        .HasColumnName("ledger_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("StakeholderType")
                        .HasColumnType("integer")
                        .HasColumnName("stakeholder_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_stakeholders");

                    b.HasIndex("LedgerId")
                        .HasDatabaseName("ix_stakeholders_ledger_id");

                    b.ToTable("stakeholders", "stakeholder");
                });

            modelBuilder.Entity("TeaManagement.Entities.TransactionDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("cr_amount");

                    b.Property<decimal>("DrAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("dr_amount");

                    b.Property<char>("DrCr")
                        .HasColumnType("character(1)")
                        .HasColumnName("dr_cr");

                    b.Property<int>("LedgerId")
                        .HasColumnType("integer")
                        .HasColumnName("ledger_id");

                    b.Property<int>("RecById")
                        .HasColumnType("integer")
                        .HasColumnName("rec_by_id");

                    b.Property<DateTime>("RecDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rec_date");

                    b.Property<char>("RecStatus")
                        .HasColumnType("character(1)")
                        .HasColumnName("rec_status");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_transaction_details");

                    b.HasIndex("LedgerId")
                        .HasDatabaseName("ix_transaction_details_ledger_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_transaction_details_transaction_id");

                    b.ToTable("transaction_details", "accounting");
                });

            modelBuilder.Entity("TeaManagement.Entities.AddBonus", b =>
                {
                    b.HasOne("TeaManagement.Entities.NewFactory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bonus_factory_factory_id");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("TeaManagement.Entities.NewFactory", b =>
                {
                    b.HasOne("TeaManagement.Entities.Ledger", "Ledger")
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_factory_ledger_ledger_id");

                    b.Navigation("Ledger");
                });

            modelBuilder.Entity("TeaManagement.Entities.Product", b =>
                {
                    b.HasOne("TeaManagement.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_product_category_category_id");

                    b.HasOne("TeaManagement.Entities.ProductUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_unit_unit_id");

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TeaManagement.Entities.Receivable", b =>
                {
                    b.HasOne("TeaManagement.Entities.Stakeholder", "Stakeholder")
                        .WithMany()
                        .HasForeignKey("StakeholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receivable_stakeholders_stakeholder_id");

                    b.HasOne("TeaManagement.Entities.AccountingTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receivable_transactions_transaction_id");

                    b.Navigation("Stakeholder");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TeaManagement.Entities.Sale", b =>
                {
                    b.HasOne("TeaManagement.Entities.NewFactory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_factory_factory_id");

                    b.HasOne("TeaManagement.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_product_product_id");

                    b.Navigation("Factory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TeaManagement.Entities.Stakeholder", b =>
                {
                    b.HasOne("TeaManagement.Entities.Ledger", "Ledger")
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stakeholders_ledger_ledger_id");

                    b.Navigation("Ledger");
                });

            modelBuilder.Entity("TeaManagement.Entities.TransactionDetails", b =>
                {
                    b.HasOne("TeaManagement.Entities.Ledger", "Ledger")
                        .WithMany()
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_details_ledger_ledger_id");

                    b.HasOne("TeaManagement.Entities.AccountingTransaction", "Transaction")
                        .WithMany("Details")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_details_transactions_transaction_id");

                    b.Navigation("Ledger");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TeaManagement.Entities.AccountingTransaction", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
